services:
  goobie-bot:
    build:
      context: .
    container_name: goobie-bot-prod
    env_file: .env
    restart: unless-stopped
    # Pi-specific environment variables (optimized for single bot on Pi 2)
    environment:
      - PI_MODE=true
      - MEMORY_LIMIT_MB=512
      - CACHE_SIZE_LIMIT=100
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    # Resource limits for Pi 2 Model B (1GB RAM, quad-core) - Single Bot Optimization
    # Note: Docker Compose V1 doesn't support deploy.resources
    # Use docker run with --memory and --cpus for resource limits
    mem_limit: 768M # 75% of 1GB RAM (single bot gets more resources)
    cpus: 2.0 # 2 cores (50% of quad-core for better performance)
    # Health check for Pi monitoring
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import psutil; exit(0 if psutil.virtual_memory().percent < 90 else 1)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Labels for management
    labels:
      - "com.goobie-bot.service=discord-bot"
      - "com.goobie-bot.environment=pi-production"
      - "com.goobie-bot.architecture=armv7"
    # Security options
    security_opt:
      - no-new-privileges:true
    # Use default bridge network (more secure for Discord bot)
    # network_mode: "host"  # Not needed for Discord bot
